### PR TITLE
Use guava Cache instead of HashMap for concurrency

### LINKED ISSUE #591: How to parallelize?
I use `javaView.getClasses().parallelStream()` to retrieve some information for all classes.

But it throws `java.util.ConcurrentModificationException`:
```
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1229)
	at sootup.java.core.JavaIdentifierFactory.getPackageName(JavaIdentifierFactory.java:254)
Caused by: java.util.ConcurrentModificationException
	at sootup.java.core.JavaIdentifierFactory.getClassType(JavaIdentifierFactory.java:108)
	at sootup.java.core.JavaIdentifierFactory.getClassType(JavaIdentifierFactory.java:122)
	at sootup.java.core.JavaIdentifierFactory.lambda$getType$1(JavaIdentifierFactory.java:175)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at sootup.java.core.JavaIdentifierFactory.getType(JavaIdentifierFactory.java:175)
	at sootup.java.bytecode.frontend.AsmUtil.toJimpleType(AsmUtil.java:200)
	at sootup.java.bytecode.frontend.AsmClassSource.lambda$resolveFields$0(AsmClassSource.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at sootup.java.bytecode.frontend.AsmClassSource.resolveFields(AsmClassSource.java:75)
	at sootup.java.bytecode.frontend.AsmClassSource.resolveFields(AsmClassSource.java:147)
	at sootup.core.model.SootClass.lazyFieldInitializer(SootClass.java:63)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:166)
	at sootup.core.model.SootClass.getFields(SootClass.java:106)
	at sootup.java.core.JavaSootClass.getFields(JavaSootClass.java:109)
```

It seems that `sootup.java.core.JavaIdentifierFactory` is still a global singleton and in this class `java.util.HashMap` is used for cache, which doesn't support concurrency.

Is that exception expected? What is the correct way to parallelize?

### PR DESCRIPTION
**Pull request by ceclin**
Fix #591

According to [guava wiki](https://github.com/google/guava/wiki/MapMakerMigration), I use CacheBuilder instead of MapMaker.

### CODE REVIEW

**Comment by swissiety** [comment]
looks good to me.
It would be great if we can replace those `.asMap()`'s ...`.computeIfAbsent()`'s with `CacheLoader`'s and a simple `.get()`'s . That way, in case of a cache miss a new instance is created on demand. This removes the overhead for creating a temporary view on the map every time.

**Comment by ceclin** [comment]
Firstly, if we use `CacheBuilder.newBuilder().weakValues().build(CacheLoader.from(key -> ...))`, there will be another problem. The logic for creating instance for missing value must be defined during the initialization. The cache field is declared in class `JavaIdentifierFactory`, but `JavaModuleIdentifierFactory` use a different logic for creating missing instance other than `JavaIdentifierFactory`. If we don't want to use `asMap()`, I think it needs more modification to the codebase than `asMap()`.

Secondly, `asMap()` doesn't create any temporary object. It just returns its member `localCache`:
https://github.com/google/guava/blob/8f8082e96b12202dcef32cc2b7c4c91e6ba1b72b/android/guava/src/com/google/common/cache/LocalCache.java#L4789-L4792

**Review by swissiety — APPROVED** [review]

**Comment by swissiety** [comment]
thanks for the hints. While we are already caching the PackageName's - we are currently inconsequently not doing it for the ClassTypes as well.. would you mind to apply the same strategy for caching `ClassType`s into `getClassType(..)` ?

**Comment by ceclin** [comment]
> thanks for the hints. While we are already caching the PackageName's - we are currently inconsequently not doing it for the ClassTypes as well.. would you mind to apply the same strategy for caching `ClassType`s into `getClassType(..)` ?

Sorry, I am too busy these days to work on it. I may create a new PR for it when I have time.

**Pull request merged**
