### PR TITLE
precompute toString for JavaClassType and SootClassMemberSignature

### PR DESCRIPTION
**Pull request by Liyw979**
like https://github.com/soot-oss/SootUp/pull/881 :)

### CODE REVIEW

**Comment by stschott** [comment]
Can you please describe your potential use case for this change? At the moment, in contrast to the hashcode change, we are not sure whether the trade-off in additional memory used is worth the time save.

**Comment by Liyw979** [comment]
I'm doing somthing like symbolic execution, and When I put `method.getSignature()` in my code, it gets executed 1000000 times in my simulation. 😅

**Comment by swissiety** [comment]
Do you actually need `toString()` there? I mean it depends on your use case but I stumbled over usage examples where `==` or `equals()` did the (better) job.

**Comment by Liyw979** [comment]
Maybe we can do something like https://github.com/soot-oss/SootUp/blob/bf95782b1ec8f268d64a19748af5412031342273/sootup.core/src/main/java/sootup/core/model/SootMethod.java#L172-L178

**Comment by Liyw979** [comment]
> Do you actually need `toString()` there? I mean it depends on your use case but I stumbled over usage examples where `==` or `equals()` did the (better) job.

I will try this.

**Pull request closed without merging**
