### PR TITLE
Close traps on the last iterated block in BlockGraphIteratorAndTrapAggregator 

### LINKED ISSUE #895: fix BlockGraphIteratorAndTrapAggregator to handle traps closing on the last iterated block
I've encountered a problem while analyzing the following Java 8 code:

``` java
public class TryWithResourcesFinally {

	public static void nop() {}

	public void test0(final AutoCloseable ac0) throws Exception {
		try (AutoCloseable ac1 = ac0) {
			nop();
		} finally {
			throw new Exception();
		}
	}
}
```

This code generates a block graph whose last element (in topological order) closes a trap. For the example above this corresponds to block 21 in the corresponding [graph](http://magjac.com/graphviz-visual-editor/?dot=digraph%20G%20%7B%0A%09compound%3Dtrue%0A%09labelloc%3Db%0A%09style%3Dfilled%0A%09color%3Dgray90%0A%09node%20%5Bshape%3Dbox%2Cstyle%3Dfilled%2Ccolor%3Dwhite%5D%0A%09edge%20%5Bfontsize%3D10%2Carrowsize%3D1.5%2Cfontcolor%3Dgrey40%5D%0A%09fontsize%3D10%0A%0A%2F%2F%20%20lines%20%5B9%3A%209%5D%20%0A%09subgraph%20cluster_1807015220%20%7B%20%0A%09%09label%20%3D%20%22Block%20%231%22%0A%09%09718571091%5Blabel%3D%22this%20%3A%3D%20%40this%3A%20TryWithResourcesFinally%22%2Cshape%3DMdiamond%2Ccolor%3Dgrey50%2Cfillcolor%3Dwhite%5D%0A%09%092107577743%5Blabel%3D%22l1%20%3A%3D%20%40parameter0%3A%20java.lang.AutoCloseable%22%5D%0A%0A%09%09718571091%20-%3E%202107577743%0A%09%7D%0A%092107577743%3As%20-%3E%201117871068%3An%0A%0A%2F%2F%20%20lines%20%5B9%3A%209%5D%20%0A%09subgraph%20cluster_102174918%20%7B%20%0A%09%09label%20%3D%20%22Block%20%232%22%0A%09%091117871068%5Blabel%3D%22l2%20%3D%20l1%22%5D%0A%09%091151704483%5Blabel%3D%22l3%20%3D%20null%22%5D%0A%0A%09%091117871068%20-%3E%201151704483%0A%09%7D%0A%091151704483%3As%20-%3E%201342346098%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091151704483%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_102174918%22%5D%0A%0A%2F%2F%20%20lines%20%5B10%3A%2010%5D%20%0A%09subgraph%20cluster_788625466%20%7B%20%0A%09%09label%20%3D%20%22Block%20%233%22%0A%09%091342346098%5Blabel%3D%22staticinvoke%20%26lt%3BTryWithResourcesFinally%3A%20void%20nop%28%29%26gt%3B%28%29%22%5D%0A%09%7D%0A%091342346098%3As%20-%3E%20610454273%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091342346098%3Ae%20-%3E%20508378341%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_788625466%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1095273238%20%7B%20%0A%09%09label%20%3D%20%22Block%20%234%22%0A%09%09610454273%5Blabel%3D%22if%20l1%20%3D%3D%20null%22%5D%0A%09%7D%0A%09610454273%3As%20-%3E%20431506362%3An%5Blabel%3D%22false%22%5D%0A%09610454273%3As%20-%3E%202024240125%3An%5Blabel%3D%22true%22%5D%0A%09%2F%2Fexceptional%20edges%20%0A%09610454273%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1095273238%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_177140066%20%7B%20%0A%09%09label%20%3D%20%22Block%20%235%22%0A%09%09431506362%5Blabel%3D%22if%20null%20%3D%3D%20null%22%5D%0A%09%7D%0A%09431506362%3As%20-%3E%201693226694%3An%5Blabel%3D%22false%22%5D%0A%09431506362%3As%20-%3E%201164799006%3An%5Blabel%3D%22true%22%5D%0A%09%2F%2Fexceptional%20edges%20%0A%09431506362%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_177140066%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_2059572982%20%7B%20%0A%09%09label%20%3D%20%22Block%20%236%22%0A%09%091693226694%5Blabel%3D%22interfaceinvoke%20l1.%26lt%3Bjava.lang.AutoCloseable%3A%20void%20close%28%29%26gt%3B%28%29%22%5D%0A%09%7D%0A%091693226694%3As%20-%3E%201569754439%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091693226694%3Ae%20-%3E%20511832416%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_2059572982%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_375466577%20%7B%20%0A%09%09label%20%3D%20%22Block%20%237%22%0A%09%091569754439%5Blabel%3D%22goto%22%5D%0A%09%7D%0A%091569754439%3As%20-%3E%202024240125%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091569754439%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_375466577%22%5D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%20-1%5D%20%0A%09subgraph%20cluster_2104973502%20%7B%20%0A%09%09label%20%3D%20%22Block%20%238%22%0A%09%09294111720%5Blabel%3D%22%24stack9%20%3A%3D%20%40caughtexception%22%5D%0A%09%091261764601%5Blabel%3D%22l7%20%3D%20%24stack9%22%5D%0A%0A%09%09294111720%20-%3E%201261764601%0A%09%7D%0A%091261764601%3As%20-%3E%201070044969%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091261764601%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_2104973502%22%5D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%20-1%5D%20%0A%09subgraph%20cluster_1046665075%20%7B%20%0A%09%09label%20%3D%20%22Block%20%239%22%0A%09%091070044969%5Blabel%3D%22%24stack10%20%3D%20new%20java.lang.Exception%22%5D%0A%09%09888557915%5Blabel%3D%22%23l3%20%3D%20%28java.lang.Exception%29%20%24stack10%22%5D%0A%09%091800976873%5Blabel%3D%22specialinvoke%20%23l3.%26lt%3Bjava.lang.Exception%3A%20void%20%26lt%3Binit%26gt%3B%28%29%26gt%3B%28%29%22%5D%0A%09%09949767857%5Blabel%3D%22%23l2%20%3D%20%28java.lang.Throwable%29%20%24stack10%22%5D%0A%09%09253011924%5Blabel%3D%22throw%20%23l2%22%2Cshape%3DMdiamond%2Ccolor%3Dgrey50%2Cfillcolor%3Dwhite%5D%0A%0A%09%091070044969%20-%3E%20888557915%20-%3E%201800976873%20-%3E%20949767857%20-%3E%20253011924%0A%09%7D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%20-1%5D%20%0A%09subgraph%20cluster_2029680286%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2310%22%0A%09%09511832416%5Blabel%3D%22%24stack14%20%3A%3D%20%40caughtexception%22%5D%0A%09%09110651474%5Blabel%3D%22l4%230%20%3D%20%24stack14%22%5D%0A%09%0928094269%5Blabel%3D%22virtualinvoke%20l3.%26lt%3Bjava.lang.Throwable%3A%20void%20addSuppressed%28java.lang.Throwable%29%26gt%3B%28%24stack14%29%22%5D%0A%09%091003292107%5Blabel%3D%22goto%22%5D%0A%0A%09%09511832416%20-%3E%20110651474%20-%3E%2028094269%20-%3E%201003292107%0A%09%7D%0A%091003292107%3As%20-%3E%202024240125%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091003292107%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_2029680286%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_36657658%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2311%22%0A%09%091164799006%5Blabel%3D%22interfaceinvoke%20l1.%26lt%3Bjava.lang.AutoCloseable%3A%20void%20close%28%29%26gt%3B%28%29%22%5D%0A%09%091179792105%5Blabel%3D%22goto%22%5D%0A%0A%09%091164799006%20-%3E%201179792105%0A%09%7D%0A%091179792105%3As%20-%3E%202024240125%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091179792105%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_36657658%22%5D%0A%0A%2F%2F%20%20lines%20%5B12%3A%2012%5D%20%0A%09subgraph%20cluster_787122337%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2312%22%0A%09%092024240125%5Blabel%3D%22%24stack8%20%3D%20new%20java.lang.Exception%22%5D%0A%09%09335580595%5Blabel%3D%22%23l1%20%3D%20%28java.lang.Exception%29%20%24stack8%22%5D%0A%09%091390913202%5Blabel%3D%22specialinvoke%20%23l1.%26lt%3Bjava.lang.Exception%3A%20void%20%26lt%3Binit%26gt%3B%28%29%26gt%3B%28%29%22%5D%0A%09%09310016558%5Blabel%3D%22%23l0%20%3D%20%28java.lang.Throwable%29%20%24stack8%22%5D%0A%09%091245065720%5Blabel%3D%22throw%20%23l0%22%2Cshape%3DMdiamond%2Ccolor%3Dgrey50%2Cfillcolor%3Dwhite%5D%0A%0A%09%092024240125%20-%3E%20335580595%20-%3E%201390913202%20-%3E%20310016558%20-%3E%201245065720%0A%09%7D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%209%5D%20%0A%09subgraph%20cluster_1753714541%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2313%22%0A%09%09508378341%5Blabel%3D%22%24stack13%20%3A%3D%20%40caughtexception%22%5D%0A%09%091263634860%5Blabel%3D%22l4%231%20%3D%20%24stack13%22%5D%0A%09%091037854997%5Blabel%3D%22l3%20%3D%20%24stack13%22%5D%0A%09%091884155890%5Blabel%3D%22throw%20%24stack13%22%2Cshape%3DMdiamond%2Ccolor%3Dgrey50%2Cfillcolor%3Dwhite%5D%0A%0A%09%09508378341%20-%3E%201263634860%20-%3E%201037854997%20-%3E%201884155890%0A%09%7D%0A%09%2F%2Fexceptional%20edges%20%0A%091884155890%3Ae%20-%3E%201703696921%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1753714541%22%5D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%2011%5D%20%0A%09subgraph%20cluster_127791068%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2314%22%0A%09%091703696921%5Blabel%3D%22%24stack12%20%3A%3D%20%40caughtexception%22%5D%0A%09%091507118393%5Blabel%3D%22l5%20%3D%20%24stack12%22%5D%0A%0A%09%091703696921%20-%3E%201507118393%0A%09%7D%0A%091507118393%3As%20-%3E%201160649162%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091507118393%3Ae%20-%3E%201703696921%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_127791068%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1481818223%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2315%22%0A%09%091160649162%5Blabel%3D%22if%20l1%20%3D%3D%20null%22%5D%0A%09%7D%0A%091160649162%3As%20-%3E%20932582590%3An%5Blabel%3D%22false%22%5D%0A%091160649162%3As%20-%3E%2069329761%3An%5Blabel%3D%22true%22%5D%0A%09%2F%2Fexceptional%20edges%20%0A%091160649162%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1481818223%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1095352419%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2316%22%0A%09%09932582590%5Blabel%3D%22if%20%24stack13%20%3D%3D%20null%22%5D%0A%09%7D%0A%09932582590%3As%20-%3E%201871612052%3An%5Blabel%3D%22false%22%5D%0A%09932582590%3As%20-%3E%20153646652%3An%5Blabel%3D%22true%22%5D%0A%09%2F%2Fexceptional%20edges%20%0A%09932582590%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1095352419%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_951031848%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2317%22%0A%09%091871612052%5Blabel%3D%22interfaceinvoke%20l1.%26lt%3Bjava.lang.AutoCloseable%3A%20void%20close%28%29%26gt%3B%28%29%22%5D%0A%09%7D%0A%091871612052%3As%20-%3E%201330247343%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091871612052%3Ae%20-%3E%20170949260%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_951031848%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1408482749%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2318%22%0A%09%091330247343%5Blabel%3D%22goto%22%5D%0A%09%7D%0A%091330247343%3As%20-%3E%2069329761%3An%0A%09%2F%2Fexceptional%20edges%20%0A%091330247343%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1408482749%22%5D%0A%0A%2F%2F%20%20lines%20%5B-1%3A%20-1%5D%20%0A%09subgraph%20cluster_400103862%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2319%22%0A%09%09170949260%5Blabel%3D%22%24stack11%20%3A%3D%20%40caughtexception%22%5D%0A%09%09731829978%5Blabel%3D%22l6%20%3D%20%24stack11%22%5D%0A%09%091845623216%5Blabel%3D%22virtualinvoke%20l3.%26lt%3Bjava.lang.Throwable%3A%20void%20addSuppressed%28java.lang.Throwable%29%26gt%3B%28%24stack11%29%22%5D%0A%09%09993370665%5Blabel%3D%22goto%22%5D%0A%0A%09%09170949260%20-%3E%20731829978%20-%3E%201845623216%20-%3E%20993370665%0A%09%7D%0A%09993370665%3As%20-%3E%2069329761%3An%0A%09%2F%2Fexceptional%20edges%20%0A%09993370665%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_400103862%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1650813924%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2320%22%0A%09%09153646652%5Blabel%3D%22interfaceinvoke%20l1.%26lt%3Bjava.lang.AutoCloseable%3A%20void%20close%28%29%26gt%3B%28%29%22%5D%0A%09%7D%0A%09153646652%3As%20-%3E%2069329761%3An%0A%09%2F%2Fexceptional%20edges%20%0A%09153646652%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1650813924%22%5D%0A%0A%2F%2F%20%20lines%20%5B11%3A%2011%5D%20%0A%09subgraph%20cluster_1991278377%20%7B%20%0A%09%09label%20%3D%20%22Block%20%2321%22%0A%09%0969329761%5Blabel%3D%22throw%20%24stack12%22%2Cshape%3DMdiamond%2Ccolor%3Dgrey50%2Cfillcolor%3Dwhite%5D%0A%09%7D%0A%09%2F%2Fexceptional%20edges%20%0A%0969329761%3Ae%20-%3E%20294111720%3An%20%5Blabel%3D%22%09java.lang.Throwable%22color%3Dred%2Cltail%3D%22cluster_1991278377%22%5D%0A%0A%7D).

Retrieving the traps of this block graph using `sootup.core.graph.StmtGraph$BlockGraphIteratorAndTrapAggregator` will result in the error:
```
java.lang.IllegalArgumentException: Invalid StmtGraph. A Trap is not created as a traps endStmt was not visited during the iteration of all Stmts.

	at sootup.core.graph.StmtGraph$BlockGraphIteratorAndTrapAggregator.getTraps(StmtGraph.java:505)
	at sootup.core.graph.MutableBlockStmtGraph.getTraps(MutableBlockStmtGraph.java:1495)
	at sootup.core.graph.ForwardingStmtGraph.getTraps(ForwardingStmtGraph.java:136)
	at sootup.core.graph.StmtGraph.getLabeledStmts(StmtGraph.java:718)
	at sootup.core.util.printer.LabeledStmtPrinter.getStmts(LabeledStmtPrinter.java:116)
	at sootup.core.util.printer.LabeledStmtPrinter.initializeSootMethod(LabeledStmtPrinter.java:110)
	at sootup.core.util.printer.JimplePrinter.printStmts(JimplePrinter.java:327)
	at sootup.core.util.printer.JimplePrinter.printStatementsInBody(JimplePrinter.java:323)
	at sootup.core.util.printer.JimplePrinter.printBody(JimplePrinter.java:310)
	at sootup.core.util.printer.JimplePrinter.printTo(JimplePrinter.java:275)
	at sootup.core.util.printer.JimplePrinter.printTo(JimplePrinter.java:266)
	at sootup.core.model.Body.toString(Body.java:226)
	at java.base/java.lang.String.valueOf(String.java:4216)
	at java.base/java.io.PrintStream.println(PrintStream.java:1047)
	at sootup.java.bytecode.TryWithResourcesFinallyTests.lambda$test$0(TryWithResourcesFinallyTests.java:23)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at sootup.java.bytecode.TryWithResourcesFinallyTests.test(TryWithResourcesFinallyTests.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

This can be fixed by closing the traps on the last block after the iterations of the aggregator.

### PR DESCRIPTION
**Pull request by paganma**
Fixes  #895

### CODE REVIEW

**Comment by swissiety** [comment]
I think we already had this approach before - the problem is: the trap end is exclusive so this approach would lead to a smaller trap range than actually. The problem the thrown exception points out arises already inside the blockgraphiterator which determines the topological order of the stmts - We need to sort the stmts differenty - i. E. The last stmt has to be one that can not have an exceptionrange (e.g. JReturn* - with jthrowstmt it can only be the last stmt if we dont catch the exception in the same method)

**Comment by paganma** [comment]
Okay, later I will look into a way to enforce this order in the BlockGraphIterator superclass. From what I understand we need to modify the scheduling so that if a fallsthrough sequence only has exceptional successors it should be given higher priority.

**Comment by paganma** [comment]
I tried to sort the blocks differently but if I have to be honest I can't quite find a solution that may work for every case. Even if we can use heuristics to sort the iteration of the blocks in such a way that the last one does not have an exception range, technically it is always possible to easily construct a graph where there is no other way to sort it. The simplest example I can come up with is that of a body with a single exceptional loop. While I know that this type of construct in practice is hard to come by, I would prefer not to resort to a solution that may break other edge cases. Do you have any observation with respect to these cases?

**Comment by swissiety** [comment]
fixed in of #922

**Pull request closed without merging**
