### PR TITLE
Migrate test system from junit 4 to junit 5

### PR DESCRIPTION
**Pull request by JonasKlauke**
Update all tests to the API changes in juint 5

### CODE REVIEW

**Review by swissiety — CHANGES_REQUESTED** [review]
good work! 

To avoid `@Tag` problems with typos lets replace `@Tag\(\"Java([8|9])\"\)` by `@Tag(TestCategories.JAVA_$i_CATEGORY)` and add a categories class file to each module like its done in the bytecode module ( or can we move it to core and reuse it in the other modules?)

**Comment by swissiety** [comment]
just from the added timing in the java8 run (+2minutes) I would assume the testwatcher is not caching?
- [x] investigate

**Comment by JonasKlauke** [comment]
I added on many testclasses a Tag which had no category before. That could be the reason. Since we also gained coverage

**Comment by JonasKlauke** [comment]
The Enum Tag is good and yeah we should go for only one Enum. If every module imports core then we can simply put it there

**Comment by JonasKlauke** [comment]
Enum moved to #859

**Review by swissiety — APPROVED** [review]

**Pull request merged**
