### PR TITLE
Fix switch comparison

### PR DESCRIPTION
**Pull request by stschott**

### CODE REVIEW

**Review by swissiety — APPROVED** [review]
:+1:

**Comment by swissiety** [comment]
hmm... `MutableBlockStmtGraphTest.testRemoveMultipleTrapsWithDifferentExceptionTypes:1098 » IllegalArgument Invalid StmtGraph. A Trap is not created as a traps endStmt was not visited during the iteration of all Stmts.`

**Comment by stschott** [comment]
Flaky test? Locally the test case passes.

**Comment by stschott** [comment]
The only method I changed is not even called when running the `MutableBlockStmtGraphTest.testRemoveMultipleTrapsWithDifferentExceptionTypes` test.

**Pull request merged**
