### PR TITLE
Fix Aggregator, TypeAssigner, LocalNameStandardizer

### LINKED ISSUE #739: Aggregator type cast bug
```java
public class Main  {
  public static void main(String[] args) {
    int a = Integer.valueOf(args[0]);
    int b = a;
    int c = b;
    System.out.println(a + b + c);

  }
}
```

and then enable body interceptor

```kotlin
view.configBodyInterceptors{
        BytecodeClassLoadingOptions.Default
    }
```

```
java.lang.IllegalStateException: Failed to apply sootup.java.bytecode.interceptors.Aggregator@662ac478 to <Main: void main(java.lang.String[])>
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:229)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
Caused by: java.lang.ClassCastException: class sootup.core.jimple.common.expr.JAddExpr cannot be cast to class sootup.core.jimple.basic.Immediate (sootup.core.jimple.common.expr.JAddExpr and sootup.core.jimple.basic.Immediate are in unnamed module of loader 'app')
	at sootup.java.bytecode.interceptors.Aggregator.interceptBody(Aggregator.java:196)
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:226)
	... 13 more
```

image

### PR DESCRIPTION
**Pull request by swissiety**
- [x] TypeAssigner: 'found' Bottomtype to UnknownType
- [x] LocalNameStanrdizer: dont handle Local Types where no standard Type is given
- [x] fix Aggregator doing changes on Stmts like:
from (`AggregatorTest.testIssue739()`):
```
    $l0 := @parameter0: java.lang.String[];
    $stack4 = $l0[0];
    $stack5 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(java.lang.String)>($stack4);
    $l1 = virtualinvoke $stack5.<java.lang.Integer: int intValue()>();
```
to (which is wrong; missing staticinvoke, wrong cast to Integer insetad of String)
```
    $l0 := @parameter0: java.lang.String[];
    $stack5 = $l0[0];
    $#l0 = (java.lang.Integer) $stack5;
    $l1 = virtualinvoke $#l0.<java.lang.Integer: int intValue()>();
```

- [x] fix Aggregator to not remove a needed Stmt in `AggregatorTest.testIssue739()`:
```
    $stack6 = $l1 + $l1;   // removed
    $stack7 = $stack6 + $l1;
``` 

closes #739

### CODE REVIEW

**Comment by swissiety** [comment]
@JonasKlauke SourcteType already works in finding the entryMethod ;-)

**Comment by virusdefender** [comment]
Run my code with this branch ( and with `BytecodeClassLoadingOptions.Default` ), if some type class is not found, `Could not find xxx in View` Exception will be thrown.

[Target_jsp.class.zip](https://github.com/soot-oss/SootUp/files/13281908/Target_jsp.class.zip)

```
java.lang.IllegalStateException: Failed to apply sootup.java.bytecode.interceptors.TypeAssigner@16eccb2e to <Target_jsp: org.apache.tomcat.InstanceManager _jsp_getInstanceManager()>
        at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:229)
        at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
        at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
        at sootup.core.util.printer.JimplePrinter.printMethods(JimplePrinter.java:242)
        at sootup.core.util.printer.JimplePrinter.printTo(JimplePrinter.java:210)
        at com.cloudwalker.javawebshell.main.SootUpCommand.run(Main.kt:311)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
       
Caused by: java.lang.IllegalArgumentException: Could not find org.apache.jasper.runtime.HttpJspBase in View.
        at sootup.core.views.View.lambda$getClassOrThrow$0(View.java:90)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at sootup.core.views.View.getClassOrThrow(View.java:89)
        at sootup.core.typehierarchy.ViewTypeHierarchy.sootClassFor(ViewTypeHierarchy.java:421)
        at sootup.core.typehierarchy.ViewTypeHierarchy.superClassOf(ViewTypeHierarchy.java:302)
        at sootup.java.bytecode.interceptors.typeresolving.BytecodeHierarchy.buildAncestryPaths(BytecodeHierarchy.java:236)
        at sootup.java.bytecode.interceptors.typeresolving.BytecodeHierarchy.getLeastCommonAncestor(BytecodeHierarchy.java:170)
        at sootup.java.bytecode.interceptors.typeresolving.TypeResolver.applyAssignmentConstraint(TypeResolver.java:209)
        at sootup.java.bytecode.interceptors.typeresolving.TypeResolver.resolve(TypeResolver.java:65)
        at sootup.java.bytecode.interceptors.TypeAssigner.interceptBody(TypeAssigner.java:42)
        at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:226)
        ... 15 more
```

While I indeed didn't add the corresponding jar of this class to the classpath, isn't it sufficient to construct the type information in Jimple only relying on the information in the class file?

**Comment by swissiety** [comment]
@virusdefender thx, this should be fixed in #[b270b08](https://github.com/soot-oss/SootUp/pull/741/commits/b270b08721be0f854d9facd878ece810aa9dda51)

**Comment by virusdefender** [comment]
thanks, it's much better now than before, but there are still a few small issues

#### method return value is not assigned to variable

```
unknown $stack0;

staticinvoke <javax.servlet.jsp.JspFactory: javax.servlet.jsp.JspFactory getDefaultFactory()>();
<$package.Target_jsp: javax.servlet.jsp.JspFactory _jspxFactory> = $stack0;
```

the return value of `getDefaultFactory` is not assigned to `stack0`

```
staticinvoke <java.lang.Runtime: java.lang.Runtime getRuntime()>();
...
$r4 = virtualinvoke $stack24.<java.lang.Runtime: java.lang.Process exec(java.lang.String[])>($r17);
```

the same case, `stack24` should be the return value of `getRuntime()`

#### `SomeType varName = null`

```
unknown $_jspx_out, $_jspx_page_context, $stack24;
```

`_jspx_out, _jspx_page_context` are assigned to type and value null at first

image

I try to rebase this pr with https://github.com/soot-oss/SootUp/pull/742 but the problem still exists

**Comment by swissiety** [comment]
thx for the feedback - can you share your code input?

**Review by kadirayk — APPROVED** [review]

**Pull request merged**
